appstory9/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'appstory9'

urlpatterns = [
	path('', views.search_book, name="searchbook"),
	path('add-fav', views.add_fav, name="add-fav"),
	path('del-fav', views.add_fav, name="del-fav"),
	path('my-fav', views.my_fav, name="fav"),
	path('logout', views.logout, name="logout"),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls import re_path, include
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appstory6.urls')),
    path('landingpage/', include('appstory6.urls')),
    # re_path(r'landingpage', mainpage, name="mainpage"),
    # path('', include('appstory9.urls')),
    path('books/', include('appstory9.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

appstory9/models.py
from django.db import models

# Create your models here.
class FavBook(models.Model):
    title = models.CharField(max_length = 100)
    img = models.CharField(max_length=200)
    link = models.CharField(max_length = 200)
    author = models.CharField(max_length=200)

appstory9/forms.py
from django import forms


class SearchForm(forms.Form):
    search_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Search book',
    }
    title = forms.CharField(max_length = 300, label='', widget=forms.TextInput(attrs=search_attrs))

appstory9/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from .forms import SearchForm
from .models import FavBook
import requests
import json

# Create your views here.
def search_book(request):
    response = {}
    response['form'] = SearchForm()
    response['fav'] = FavBook.objects.all().count
    response['data'] = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search = cd['title']
            URL = "https://www.googleapis.com/books/v1/volumes?q=" + search
            get_json = requests.get(URL).json()
            json_dict = json.dumps(get_json)
            response['data'] = json_dict
            response['fav'] = FavBook.objects.all().count
        return render(request, "searchbook.html", response)
    else:
        return render(request, "searchbook.html", response)

    if request.user.is_authenticated:
                if 'counter' not in request.session:
                    request.session['counter'] = 0
                count = request.session['counter']
                response['counter'] = count
                if 'nama' not in request.session:
                    request.session['nama'] = request.user.username
                if 'email' not in request.session:
                    request.session['email'] = request.user.email
        return render(request, "searchbook.html", response)
    
    else:
        if request.user.is_authenticated:
            print(request.user.username)
            if 'nama' not in request.session:
                    request.session['nama'] = request.user.username
            if 'email' not in request.session:
                request.session['email'] = request.user.email
            if 'counter' not in request.session:
                request.session['counter'] = 0
            count = request.session['counter']
            response['counter'] = count
            print(dict(request.session))
        return render(request, "searchbook.html", response)


def add_fav(request):
if request.user.is_authenticated:
    # judul = request.GET.get('judul', None)
    # link = request.GET.get('link', None)
    # img = request.GET.get('img', None)
    # author = request.GET.get('author', None)
    # fav = FavBook(title=judul, img=img, link=link, author=author)
    # fav.save()
    print(dict(request.session))
    request.session['counter'] = request.session['counter'] + 1
    print(dict(request.session))
else:
    pass
    # data = FavBook.objects.all()
    # data_json = serializers.serialize('json', data)
return HttpResponse(data_json, content_type='aplication/json')

def del_fav(request):
if request.user.is_authenticated:
    # judul = request.GET.get('judul', None)
    # del_data = FavBook.objects.filter(title=judul)
    # del_data.delete()
    # data = FavBook.objects.all()
    # data_json = serializers.serialize('json', data)
    request.session['counter'] = request.session['counter'] - 1
    print(dict(request.session))
    return HttpResponse(data_json, content_type='aplication/json')
    
def my_fav(request):
    response = {}
    response['data'] = FavBook.objects.all()
    return render(request, "fav.html", response)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/books')

appstory9/templates/fav.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <title>Search Book</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <style type="text/css">
            body{
            /*margin-left: 50px;*/
            background: linear-gradient(150deg, #FFFFE0, #FFEFD5, #FFE4B5, #FFDAB9, #EEE8AA, #F0E68C, #BDB76B);
            background-size: 400% 400%;
            /*animation: BackgroundGradient 40s ease infinite;*/
        }
        @keyframes BackgroundGradient {
            0% {background-position: 0% 50%;}
            50% {background-position: 100% 50%;}
            100% {background-position: 0% 50%;}
        }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="text-center"><br>
                <h1 style="color:  #FF6347">List Favorite Book</h1>
                <div class="col-md-12">
                    <table id = "result" class="table table-stripped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Book</th>
                                <th scope="col">Title</th>
                                <th scope="col">Author</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for item in data%}
                            <tr>
                                <th>{{forloop.counter}}</th>
                                <td><a target="_blank" href="{{item.link}}"><img src="{{item.img}}" title="{{item.title}}"></a></td>
                                <td>{{item.title}}</td>
                                <td>{{item.author}}</td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
    </body>
</html>

appstory9/templates/searchbook.html
{%load static%}
{%load staticfiles%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <title>Book</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <style type="text/css">
            body{
            /*margin-left: 50px;*/
            background: linear-gradient(150deg, #FFFFE0, #FFEFD5, #FFE4B5, #FFDAB9, #EEE8AA, #F0E68C, #BDB76B);
            background-size: 400% 400%;
            /*animation: BackgroundGradient 40s ease infinite;*/
        }
        @keyframes BackgroundGradient {
            0% {background-position: 0% 50%;}
            50% {background-position: 100% 50%;}
            100% {background-position: 0% 50%;}
        }
        </style>
    </head>

    <body>
        {% if user.is_authenticated %}
            <div class="text-center">
                <h1>Hello, {{ user.username }}</h1>
                <br>
                <button class="btn btn-danger"><a href="{% url 'appstory9:logout' %}" style="color: white">Logout</a></button>
            </div>
        {% else %}
        <div class="text-center">
            <br>
            <button class="btn btn-danger"><a href="{% url 'social:begin' 'google-oauth2' %}" style="color: white">Login with Google</a></button>
            <br>
        </div>
        {% endif %}

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center"><br>
                            <h1 style="color: #FF6347">Search Book</h1>
                        <form id="searchbook" method="POST" action= "{% url 'appstory9:searchbook'%}">
                            {% csrf_token %}
                            {{form}}
                            <br><button class="btn btn-dark">Search</button><br>
                        </form>
                        <br><br>
                    </div>
                </div>
            </div>
            <header><a style="color: black"href="{%url 'appstory9:fav'%}"><i class="fas fa-star"></i></a><span id = "count">{{fav}}</span></header>
            <div class="text-center">
            <div class="row">
                <div class="col-md-12">
                    <table id = "result" class="table table-stripped table-active">
                
                        
                    </table>
                </div>
            </div>
        </div>
        
        <script>
            {%if data%}
            var result = JSON.parse("{{data|escapejs}}");
            $("#result").append("<thead><tr><th scope=\"col\">No</th><th scope=\"col\">Favorite</th><th scope=\"col\">Book</th><th scope=\"col\">Title</th><th scope=\"col\">Author</th></tr></thead><tbody>");
            for (i=0; i<result.items.length; i++) {
                var judult = "<td class=\"judul\">" + result.items[i].volumeInfo.title + "</td>";
                var authort = "<td class=\"author\">"+ result.items[i].volumeInfo.authors + "</td>";
                var nomor = "<tr id=\"item-"+ i+1 + "\">";
                var roww = "<th scope="+ "\"row\">" + (i+1) + "</th>";
                var star = "<td><i title=\"Favorite\" class=\"fav far fa-star\"></td>"
                var link = "<td><a target=\"_blank\" href=\""+ result.items[i].volumeInfo.infoLink + "\">"+ "<img src=\"" + result.items[i].volumeInfo.imageLinks.thumbnail + "\">" + "</a></td>"
                $("#result").append(nomor + roww + star + link + judult + authort + "</tr>");
                }
                $("#result").append("</tbody>");
            {%endif%}
        </script>
        <script src="{%static 'js/searchbook.js'%}"></script>
    </body>
</html>